### PR TITLE
Feature/source command

### PR DESCRIPTION
**Pull request by ReneganRonin**
# Synopsis:
Very basic source command.
Usage examples:
1. `source`, `source repo`, and `source repository`: Returns the Github repository url of HojBot.
2. `source help`: Returns the usage of source command.

### CODE REVIEW

**Comment by Azzaare** [comment]
@ReneganRonin can you rebase your branch on `feature/source_command` from this repo and push again?
It is ready to be merged (I just updated with the last merged PR that refactored a consequent part of the code)

**Comment by Azzaare** [comment]
I have no time to test that today. If @rmsrosa or @tk3369 is motivated enough, please review it.

Otherwise, I will try to merge it tomorrow :D

In any case, thanks @ReneganRonin

**Comment by tk3369** [comment]
I like the idea of sending a link to the HoJBot repo! 

How about we make it more functional as follows?
* `src`: returns the main repo url
* `src <command>`: go to the command file directly e.g. https://github.com/Humans-of-Julia/HoJBot.jl/blob/main/src/command/react.jl

The `<command>` argument can be any [currently active commands](https://github.com/Humans-of-Julia/HoJBot.jl/blob/main/src/main.jl#L1). So `src react` will reply back a url to the react.jl file.

**Comment by ReneganRonin** [comment]
we can use [Github API](https://api.github.com) or [Github.jl](https://github.com/JuliaWeb/GitHub.jl). I think it would be nice to remove `source` command and replace it with `github` command. The functionality is still there but the good thiing about having Github API is you can even do the following:
1. Retrieve issues from github repos (and of course ours)
2. Retrieve github profile (well for fun lol)
3. Retrieve pull requests
The following screenshots are taken from my other server that I am in to see how it can work and look like:
screenshot_2021-04-02_13-16-11_802406723
screenshot_2021-04-02_13-13-33_895912047

**Comment by tk3369** [comment]
Sounds like a good idea to me. Perhaps a separate command from this PR?

The `src <command>` idea is quite nice for people who wonder how we implement a specific command. When people see the source code that looks so simple, then they want to contribute 😉

**Comment by ReneganRonin** [comment]
true though. i guess i can open an issue for github command

**Comment by tk3369** [comment]
@ReneganRonin Would you like to rebase and implement what was [suggested above](https://github.com/Humans-of-Julia/HoJBot.jl/pull/31#issuecomment-811741331)?

**Comment by ReneganRonin** [comment]
I am kinda busy but I would like to do that once I am done with all my school stuff.

**Comment by ReneganRonin** [comment]
Closing in favor of #64

**Pull request closed without merging**
