### PR TITLE
Create reaction.jl

### PR DESCRIPTION
**Pull request by arubhardwaj**
in progress :)

### CODE REVIEW

**Comment by Azzaare** [comment]
I converted to draft until you think the PR is ready @arubhardwaj  :)

**Comment by arubhardwaj** [comment]
Yes, it needs some update. I actually, did not check anything after the recent update. I will get everything done by the weekend :) @Azzaare

**Review by tk3369 — COMMENTED** [review]
@arubhardwaj I've jumped the queue. It's probably better that you get the latest code and start a new PR.

**Comment by arubhardwaj** [comment]
okay, that makes sense, I am reviewing the whole code right now. Will add new reactions soon

**Pull request closed without merging**
