### PR TITLE
Add discourse command

### PR DESCRIPTION
**Pull request by tk3369**
New feature!
* Type `,discourse <query>` to run a search
* Click on the 👈 or 👉 emoji to flip to the previous/next post

Better engineering
* New code are heavily documented
* Added unit tests

image

### CODE REVIEW

**Comment by rmsrosa** [comment]
Can you check for the presence of an emoji? If so, maybe you can check whether the "point left" emoji is there already and only then react with the "point right" emoji.

**Comment by tk3369** [comment]
I don't follow.... what do you mean?

**Comment by rmsrosa** [comment]
I mean, in the part
```julia
     create(c, Reaction, new_message, "👈")
     sleep(0.01) # try to order these emojis properly with a delay
     create(c, Reaction, new_message, "👉")
```
I am suggesting waiting for the  "👈" to be present before reacting with "👉". Something like a `while no "👈"; end`. Probably something smarter to avoid an endless `while` loop, but with this idea. Provided there is a way to check whether a specific emoji reaction is present.

**Comment by tk3369** [comment]
Ah OK. Well, I’m unsure how often it will come out of order. I would keep it simple and increase the sleep time again if needed for now. We can revisit later if it becomes too annoying.

**Pull request merged**
