### PR TITLE
Update JuliaCon.jl and pass timezone

### PR DESCRIPTION
**Pull request by tk3369**
This is mostly working although I just hit a bug https://github.com/JuliaCon/JuliaCon.jl/issues/22

Just creating a Draft PR for review first.

### CODE REVIEW

**Comment by Azzaare** [comment]
I have tested the different commands. Everything seems fine (iff the server time zone is set to UTC)

**Comment by Azzaare** [comment]
So now, @rmsrosa made a good remark about a week ago. Maybe for people requesting a specific TZ, the bot could answer with a DM instead of a reply in the general chat.

What do you think @tk3369 ?

**Comment by tk3369** [comment]
Ok, this is all ready to go. I have updated the Manifest and switched to JuliaCon v2021.2.0.

**Comment by tk3369** [comment]
This branch has been used throughout JuliaCon. Just merged now.

**Pull request merged**
