### PR TITLE
Add whistle blower handler

### LINKED ISSUE #34: Community-driven auto moderation
# Background 
A primary job of moderators is to ensure a comfortable environment for community members to interact with each other. For a diverse community with people coming from different culture, background, age group, etc., it is even more important to take this seriously.

The primary problems for manual moderation are:
1. It is sometimes difficult to decide whether something is offensive
2. The mods takes a lot of effort to discuss whether the content is appropriate or should be removed
3. It takes time to reach a consensus/decision before action can be taken

# Proposed approach
I propose that we automate this moderation work with the HoJBot. It could work as follows:

1. Member A posts something inappropriate
2. Member B felt uncomfortable and reacted with an `X` emoji.
3. Member C also felt uncomfortable and reacted with an `X` emoji.
4. etc.
5. When it reaches a threshold (e.g. 3 `X`'s) then the bot removes the post and notifies the mods & member A about the removal.

So basically, we let the community decides whether something is bad.

_Originally posted by @tk3369 in https://github.com/Humans-of-Julia/HoJBot.jl/discussions/2_

### PR DESCRIPTION
**Pull request by tk3369**
Resolves #34 

Couple notes: 
1. For now, I am using the 🚷 emoji for people to report inappropriate content. It is possible to use a custom emoji if necessary. 
1. The threshold that triggers a message removal is 3.  Is that too loose or too tight? Please comment below.
1. The emoji is automatically removed immediately to protect the reporter's identity
1. A DM message is sent to the reporter, thanking their action.
1. A user can only report against the same once.

The bot should also alert Mod team & DM the member who is potentially in violation. I haven't done these yet... That should be fairly straightforward to do.

### CODE REVIEW

**Comment by Azzaare** [comment]
Thanks @tk3369 
If no one do it before, I will try to review and merge it tomorrow

**Review by rmsrosa — CHANGES_REQUESTED** [review]
1) I think a limit of 3 is fine as a start.

2) I wonder whether we should have `audit/` be a subdirectory of `data/` so we keep all data in there. I imagine we will have other stuff in the future (e.g. database for the `docstrings`, record of `function_of_the_day`, and so on). Unless you want `audit/` to be separate from the rest since it stores more sensitive information (not that much, though, just discloses who blew the whistle.

3) In the DM about the report, we could add that "Notice your reaction emoji has been instantly removed from the original message in order to keep your report anonymous from the public."

4) I miss a different message when someone already reported and it is trying to do it again. Something like "We noticed you already reported about this message. Don't worry, your whistle blow has been recorded already"...

**Comment by tk3369** [comment]
Great suggestions! In regards to the use of a separate `audit` directory, that's intentional because it does not contain data that needs to be managed. It is really just a log of records. I do see your point of organizing all command/function-specific data inside subdirectories of `data`.  I would be fine with that as well.

Now that I'm thinking more about this... the audit function should be common to all commands/handlers. It should probably take a command or handler name as field so we can analyze the log more easily later.

**Comment by tk3369** [comment]
Few changes:
* Moved audit log to `data/audit` subdirectory. For this, the log will be `data/audit/whistle.log`.
* DM message updated, including a reference number
* Some refactoring and added doc strings

**Comment by tk3369** [comment]
I think this is ready for merge.

**Review by rmsrosa — APPROVED** [review]

**Pull request merged**
